### ISSUE TITLE
bold subheadings not showing up as subheadings

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#103]
For example in http://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#enforcement-manual, the subheadings marked as `**subheadings**` show up like this:

**Appealing**Some text.

Rather than like this:

**Appealing**
Some text.

**Comment by maneesha** [comment]
Fixed with 
ce6b9514191d46 and 21c35a203e32
