### ISSUE TITLE
migrate documents from mentoring repo to here

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#106]
https://github.com/carpentries/mentoring/blob/master/mentoring-groups/resources/mentoring-session-checklist.md
https://github.com/carpentries/mentoring/blob/master/mentoring-groups/mentor-agreement.md

**Comment by ErinBecker** [comment]
These docs too: 
https://github.com/carpentries/mentoring/blob/master/onboarding-document.md
https://github.com/carpentries/mentoring/blob/master/roles/README.md

**Comment by kariljordan** [comment]
Done

**Comment by ErinBecker** [comment]
Reopening because I'm not sure if @maneesha  wanted to keep this open so she knows to deprecate the old content in the mentoring repo.

**Comment by maneesha** [comment]
Yes, I need to deprecate those pages.  I also need to spend more time cleaning up the mentoring section as referenced in #136

**Comment by kariljordan** [comment]
I know Erin did a ton last night, but if there's more work to be done on this section please let me know.

**Comment by maneesha** [comment]
All of these documents have been deprecated with a link to the mentoring section of the handbook.  Closing as I don't think there is anything else to do here.
