### ISSUE TITLE
where does trainers agreement go?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#110]
Right now it is in the handbook:  http://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html#trainer-agreement
but also in the Carpentries Policies GitHub Repo: https://github.com/carpentries/policies/blob/master/trainer-agreement.md

I think I remember @ErinBecker  saying she wanted to keep it in the policies repo but I can't remember or find that conversation now.  I will move this depending on Erin's response.

**Comment by maneesha** [comment]
Per conversation with @ErinBecker  all these kinds of agreements will be in the handbook only.

**Comment by maneesha** [comment]
Change this to "images you don't own but do have the rights to use"

**Comment by ErinBecker** [comment]
@maneesha - please deprecate the version in the policy repo.

**Comment by maneesha** [comment]
done: 
https://github.com/carpentries/policies/blob/master/trainer-agreement.md
