### ISSUE TITLE
Need instructions on publishing instructor bios to website

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#112]
Current instructions are here: https://drive.google.com/drive/folders/1cE13FvArGzQRaRZ_si5ML99cFuHbpUsY

If the instructor bio section is getting moved to the new Carpentries website soon, I'd like this to be how to build to that website rather than these old instructions.
@weaverbel  is there a timeline for this?

**Comment by maneesha** [comment]
(originally referenced in #67)

**Comment by Belinda** [comment]
I don't know how I came to be on this thread but I'm not the @Belinda you
need?

Anyway of taking me off and putting correct the one on, I've had a few of
these messages now

Cheers,

Belinda Johnstone

**Comment by maneesha** [comment]
Closing - we no longer publish bios on our website.
