### ISSUE TITLE
consistency in variable names for email templates

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#12]
Email templates include variables referring to things like dates, site names, instructor names, etc.
Some templates identify variables with square brackets, some by percent signs, some possibly other ways.

What's the preferred way to identify variables?

**Comment by ErinBecker** [comment]
In R, `[]` and `$` are both acceptable ways to identify columns in a dataframe. Can you point out specific places where you see this? I can look at it and see if it would be confusing for a newer R user.

**Comment by maneesha** [comment]
Not just for R templates.  
Some of my templates (from a browser extension) use percent signs.  
Python/Jinja uses curly braces and percent signs.

**Comment by maneesha** [comment]
And some of it is about being human readable.  Templates may not always be used from scripts.

**Comment by maneesha** [comment]
Maintainer emails use curly braces.

**Comment by jduckles** [comment]
Liquid, Jekyll and Mustache template engines all use `{{ somevariable }}`, I think that would be most readily useful.

**Comment by ErinBecker** [comment]
I don't much care which variable marking system we use. @maneesha - could you please pick one and implement across the board?

**Comment by maneesha** [comment]
Closing in favor of #44
