### ISSUE TITLE
Can't we use Jekyll?

### ISSUE THREAD

**Issue by rgaiacs** [carpentries/handbook#133]
I think that http://www.sphinx-doc.org/ and https://readthedocs.org/ are great but we aren't using them for our lessons. Have the handbook in Sphinx and Read The Docs means that contributors will have to learn two markup languages, two project organisation and two workflow. Can we migrate this to our lesson template?

**Comment by maneesha** [comment]
@rgaiacs The decision to use Read the docs was after a bit of staff discussion about the platform and the purpose of it.  The purpose of this site is different than our lessons, and we found this was the best platform to meet our needs.
