### ISSUE TITLE
check links in email templates

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#151]
Some of the email templates link to documentation that was on the website but is now in the handbook. 

E.g. the "did not complete discussion or demo" template links to the checkout checklist here: http://www.datacarpentry.org/checkout/, but should link to the version in the handbook. Where is the version in the handbook?

**Comment by maneesha** [comment]
We do not have instructor training checkout steps in the handbook.  Do we want to have a separate document with the checkout steps (separate from what's in the instuctor training curriculum?)  
We would then have to keep a checkout checklist in sync with this (http://carpentries.github.io/instructor-training/checkout/)

For example, even now, this page (http://www.datacarpentry.org/checkout/) does not specify what lessons we'd like people to contribute to, and *only* links to the DC lessons.  This page (http://carpentries.github.io/instructor-training/checkout/) does specify lessons across SWC and DC.

**Comment by ErinBecker** [comment]
This issue can be closed. The http://www.datacarpentry.org/checkout/ page now links to https://carpentries.github.io/instructor-training/checkout/, which has been updated to not mention any particular lessons.
