### ISSUE TITLE
missing blog template?

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/handbook#155]
The last item on this page http://docs.carpentries.org/topic_folders/mentoring/discussion_session_checklist.html#after-the-discussion links to a template for blog posts, but I don't see it in the repository. Should the link be removed or does someone have the template?

cc: @kariljordan

**Comment by kariljordan** [comment]
Agreed. We don't have a blog post template. We have [blog headers](https://docs.google.com/document/d/1NoNWz64-9GmavlqF1nPSmYyEzYEHwhPL-FyVE7qa36g/edit) though.

**Comment by maneesha** [comment]
Yes, and instructions on how to set up the blog headers are in the handbook:  
http://docs.carpentries.org/topic_folders/communications/submit_blog_post.html

I am deprecating the document @kariljordan  just linked to.

**Comment by fmichonneau** [comment]
I linked to an older blog post about one of the discussion session instead. Closing
