### ISSUE TITLE
Workshop Admin - Eventbrite

### ISSUE THREAD

**Issue by sheraaron** [carpentries/handbook#162]
_If needed Workshop Administrator sets up registration in Eventbrite.
If there is a registration fee, Program Manager informs Business Administrator that this will need to be refunded or applied to the workshop invoice._

How is the Program Manager notified if Eventbrite is being used? Does the Workshop Admin email the PM directly or is they are a notification from Eventbrite that goes to the PM?

**Comment by sheraaron** [comment]
@maneesha I agree. You do not need to be the middleman. In the workflow it assumes that the Program Manager is notified if there is a registration fee.

 I'd recommend, the WA notifies BA if there is a registration fee.

**Comment by maneesha** [comment]
Fixed with e7de030559
