### ISSUE TITLE
Proposing "Communications" section

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#17]
Content may include:
* How to request/create mailing lists
* How to submit blog post
* How to submit to newsletter

What else? Especially from @weaverbel

**Comment by weaverbel** [comment]
Tweets, Facebook, asking us to help with messaging, style guide - will keep thinking @maneesha

**Comment by maneesha** [comment]
Thanks @weaverbel   Please add any content you have to the drafts folder of this repo.

**Comment by weaverbel** [comment]
have done the two blog post ones - that will change once we have the merged Carpentries blog @maneesha

**Comment by maneesha** [comment]
Thanks @belinda.  What is the timeline for this?

**Comment by Belinda** [comment]
Sorry not sure how I ended up on this thread, but nothing to do with me.

**Comment by maneesha** [comment]
Thanks @weaverbel 
What is the timeline on this?

**Comment by kariljordan** [comment]
Do we need to add @thecarpentries Twitter handle? Right now we have @datacarpentry and @swcarpentry.
