### ISSUE TITLE
list of changes - readthrough

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#173]
I'm doing a readthrough of the handbook and saving a list of changes I can't make right away here so that we have a record of them: 

# Assessment
- [x] [learner assessment](https://docs.carpentries.org/topic_folders/assessment/assessment.html) links to the datacarpentry website. Will need to change link to go to The Carpentries Assessment page. 
- [x] links at bottom of [learner assessment page](https://docs.carpentries.org/topic_folders/assessment/assessment.html) should include link to long-term follow-up survey. 
- [x] [learner assessment page](https://docs.carpentries.org/topic_folders/assessment/assessment.html) should include a link to the relevant part of the assessment repo
- [x] to the Programmatic Assessment section of [the assessment page](https://docs.carpentries.org/topic_folders/assessment/assessment.html) add a short paragraph about our quarterly report schedule and links to our past Moore reports (there are three)

# Communication
- [x] Add @thecarpentries twitter feed to [Getting your news out there](https://docs.carpentries.org/topic_folders/communications/submit-news-item.html) page.
- [x] Add note about how to view list of available Slack channels for the SWC community to [Getting your news out there](https://docs.carpentries.org/topic_folders/communications/submit-news-item.html) page.
- [x] For one of the blog post instructions, the directions for listing multiple authors is wrong. One blog needs `["Name1", "Name2"]` and the other needs `["Name1, Name2"]`, but I don't remember which is which. The current document lists both as needing `["Name1", "Name2"]`.
- [x] links to Carpentry Clippings [here](https://docs.carpentries.org/topic_folders/communications/newsletter.html) and [here](https://docs.carpentries.org/topic_folders/communications/submit-news-item.html) both go to the sign-up page for the newsletter, but not to past issues. Should include link to past issues in case someone wants to see content before signing up.
- [x] Should we be linking to the live [Google doc template](https://docs.google.com/document/d/1o4Z3CQUZzGyKdax6nExijLHvOtXkzkQCcOBY27q2qk0/edit#heading=h.vs7iuvlol9b0) for the newsletter? Linking to this publically means that news items that have been put into the newsletter but not yet cleared for release will be publically available. I recommend deleting the Google doc link, especially as information about the format is already present in the handbook.

# Lesson Development
- [x] Add link from [Curriculum Advisory Committee page](https://docs.carpentries.org/topic_folders/lesson_development/lesson_development_roles.html#curriculum-advisory-committee) to [website](http://www.datacarpentry.org/lesson-leadership/) where current CAC members are listed? 
- [ ] Add missing content: Information about schedule a bug bbq and creating a Bug BBQ website is marked as "coming soon!"

**Comment by maneesha** [comment]
The Carpentries twitter feed added with 702aacfe781

**Comment by maneesha** [comment]
Assigning to @weaverbel  to follow up on Communications items in list above

**Comment by maneesha** [comment]
Assigning to @kariljordan  to follow up on Assessment items in list above

**Comment by maneesha** [comment]
Assigning to @maneesha to follow up on Programmatic assessment items in list above

**Comment by maneesha** [comment]
Newsletter links fixed with 7634996985a2c1740e662ae3c50ed6344efda3aa and c77735b50a06c72f35a5090d8d7ce763fa88c6b7

**Comment by maneesha** [comment]
How to view available slack channels fixed with 1cf6a67d2dac06a14f77425bee44f070ba4bb717

**Comment by maneesha** [comment]
learner assessment links to the datacarpentry website - fixed with d052fb6ac82e44d928de04550ef7f419b332c7a4

**Comment by maneesha** [comment]
* [learner assessment page](https://docs.carpentries.org/topic_folders/assessment/assessment.html) should include a link to the relevant part of the assessment repo 

fixed with eccc6f2d9fd1e7ee3f0342880efd9a88abcf0e69

**Comment by maneesha** [comment]
> * For one of the blog post instructions, the directions for listing multiple authors is wrong. One blog needs `["Name1", "Name2"]` and the other needs `["Name1, Name2"]`, but I don't remember which is which. The current document lists both as needing `["Name1", "Name2"]`.

Looking at existing blog posts across all four sites it looks like they all use the format  `["Name1", "Name2"]`.  Updated documentation to show multiple authors in all samples.

**Comment by maneesha** [comment]
> links at bottom of [learner assessment page](https://docs.carpentries.org/topic_folders/assessment/assessment.html) should include link to long-term follow-up survey.

fixed with ea14ad40744a15036960e98587e886db10fb14fa

**Comment by maneesha** [comment]
>  to the Programmatic Assessment section of [the assessment page](https://docs.carpentries.org/topic_folders/assessment/assessment.html) add a short paragraph about our quarterly report schedule and links to our past Moore reports (there are three)

Programmatic assessment section links directly to assessment page on Carpentries website.  I'd rather not duplicate links that are there - as we grow this will be difficult to maintain.

**Comment by maneesha** [comment]
@ErinBecker   This just leaves the sections on lesson development that need to be updated in the handbook.

For the CaC - I can link to the page on DC's website.  Can you confirm first that this is accurate and up to date?  Also do we have corresponding pages for SWC and LC?

For the Bug BBQ - do you have updates to the sections that say "coming soon"?

**Comment by libcce** [comment]
For the LC CAC, see https://librarycarpentry.org/cac/

**Comment by maneesha** [comment]
Thanks @libcce  for the LC link.

Pinging @ErinBecker  - see questions above.

**Comment by ErinBecker** [comment]
Data Carpentries page is up to date. 
No corresponding page for SWC. 
@libcce will know about LC CAC.

No updates to Bug BBQ sections. Working on writing this up for the Curriculum Development Handbook, so will have that documentation when that goes live at the end of Q1.

**Comment by maneesha** [comment]
Curriculum advisors updated with 10ffe6546f3ab19929e7f43172150ae5432d5b74

**Comment by maneesha** [comment]
@ErinBecker  Do you have updates to the Bug BBQ section?  This part of the [CDH](https://carpentries.github.io/curriculum-development/the-lesson-life-cycle.html) appears to be under development.

**Comment by maneesha** [comment]
Closing this as we have another issue for the Bug BBQ (#129)
