### ISSUE TITLE
add link to trainer training curriculum

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#181]
In the [Becoming a Trainer](https://docs.carpentries.org/topic_folders/instructor_training/trainers_training.html#trainers-training-program) section, there should be a link to the [Trainer Training Program curriculum](https://carpentries.github.io/trainer-training/). However, the schedule in the curriculum needs to be fixed first - it is currently populated with a repeat of the first weeks reading.

**Comment by maneesha** [comment]
I can add this link in, but first want to make sure from @karenword  that the other information on that page is still accurate and up to date.

**Comment by karenword** [comment]
Yes! It is always a work-in-progress, but fine to publicize :)

**Comment by maneesha** [comment]
This was done - See https://docs.carpentries.org/topic_folders/instructor_training/trainers_training.html#trainers-training-reading-schedule
