### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#186]
https://docs.carpentries.org/topic_folders/instructor_training/email_templates.html#trainee-did-pass-teaching-demo
https://docs.carpentries.org/topic_folders/instructor_training/email_templates.html#trainee-didnt-pass-teaching-demo
https://docs.carpentries.org/topic_folders/instructor_training/email_templates.html#email-after-training-event

**Comment by ErinBecker** [comment]
Looks like it should be email_templates_trainers.html instead of email_templates.html.

**Comment by tobyhodges** [comment]
There are also broken links from the Mentoring Subcommittee page. The links to the role descriptions lead to a 404.

**Comment by maneesha** [comment]
@ErinBecker  and @tobyhodges  I think these may have been fixed along the way.  Can you let me know if you still see anything wrong?

**Comment by ErinBecker** [comment]
Those appear to me to be fixed. Ok to close from me.

**Comment by tobyhodges** [comment]
Yep, the links on the mentoring page work too now. Thanks, you can close this.
