### ISSUE TITLE
Can scripts that go with email templates be public?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#19]
Right now scripts that go with email templates are in a staff google drive folder:

https://drive.google.com/drive/u/0/folders/0B2Xc7BrFgkvUTmdQZUtDcDdTWEU

Can these scripts be moved to the users guide? Should they stay somewhere else?

@ErinBecker

**Comment by ErinBecker** [comment]
There is nothing confidential in this folder, so these files can be shared. Here's a breakdown of the scripts and what their dependencies are:

1) sendmail_certificates_sep.R - Sends new instructor certificates. Requires a local copy of https://github.com/swcarpentry/certification (which is public). Includes link to SQL query to  https://data.softwarecarpentry.org/. 

2) sendmail_maintainer_certificates.R - Sends Maintainer certificates. Requires a local copy of https://github.com/swcarpentry/certification (which is public). Includes link to SQL query to  https://data.softwarecarpentry.org/. 

3) sendmail_open_training_signup.R - Notifies selected applicants to open instructor trainings that they've been selected and directs them to a sign-up sheet to choose a training event. 

4) sendmail_TTT_application.R - Notifies applicants for instructor training that their application has been received. Requires access to https://github.com/carpentries/private-data/. 

All of these scripts are set up to send from erinstellabecker@gmail.com. If run by other users, will need to change the "from =" field in the mail_certs function.

**Comment by ErinBecker** [comment]
Actually - the sendmail_open_training_signup.R script should NOT be shared, as the link to the sign-up sheet for a training event should not be made public. Our workflow assumes that the only people with access to that link are people who have been screened and accepted for instructor training. The other three are ok to share though.

**Comment by maneesha** [comment]
Closing this as #39 refers to scripts that need to be cleaned to have identifying information removed.
