### ISSUE TITLE
DC Roadmap for lesson development to handbook?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#190]
Should the Data Carpentry roadmap for lesson development go in the handbook instead of the DC website?

**Comment by maneesha** [comment]
Also this roadmap refers to SWC and DC steering committees

**Comment by maneesha** [comment]
Assigning to @fmichonneau  as it is a curriculum issue

**Comment by tobyhodges** [comment]
This topic has come up several times in discussion sessions, most recently with @orchid00 this morning.

Does the information in the roadmap still accurately reflect the process through which people should go to propose and develop new Carpentries lessons? If so, I think that this information should be added to the handbook.

I’d like to be able to answer the question with a bit more confidence next time it comes up.

**Comment by tracykteal** [comment]
It is a bit out of date, but the process is under development. 

The Vision and Plans for curriculum development blog post outlines the next steps https://carpentries.org/blog/2018/07/curriculum-vision/ and The Carpentries Curriculum Development handbook is under development https://carpentries.github.io/curriculum-development/

We could add a 'Lesson Development Roadmap' category to the handbook, and put in things that we have as well as mention that certain things are under development. Would that be a helpful starting place?

**Comment by orchid00** [comment]
To add some context, in respect to the discussion this morning with Toby @tobyhodges 
I was not referring to lessons in development, but adding that to the curriculum vision sounds great! @tracykteal

My suggestion was to have a place to share "other" lessons out there that are being used to teach similar topics (git shell, R, python, etc), could be source of **inspiration**. A low commitment suggestion can be to add a pad (I'm thinking a line on the pad of pads) where people could add links to suggested lesson materials, not official but maybe with a comment on what they do and why will they be good to share.

Also, I was wondering if the process to add a lesson to "Contributed" https://software-carpentry.org/lessons/#capstones is still on going 
> "To be considered, lessons should use our template, be hosted in an original GitHub repo (not a fork), be offered under an open license, have been taught at least once, and be actively maintained (with at least one lead maintainer). " 

I am finding many examples, and I thought will be nice to share.

**Comment by tracykteal** [comment]
Thanks @orchid00! We have a thread on 'resources for after a workshop' https://github.com/carpentries/conversations/issues/18 that I think fits with the idea of a place to share 'other' lessons. Something like an etherpad would be easier to add to and organize though. Under the 'Teaching and Hosting' section in the handbook, we could have a link to 'Other lesson resources' that points to an etherpad where people can add resources. Would that be what you were thinking about?

For the 'Contributed' lessons, we still want to do that! We're updating how to add contributed lessons as a part of the pathways for lesson contributions, to make it easier and clearer both for contributors and people who want to use the lessons. More soon!

**Comment by tobyhodges** [comment]
+1 for the etherpad idea.

Thanks all for the information. I'm looking forward to hearing more about the pathways for lesson contributions.

**Comment by orchid00** [comment]
thanks for joining the conversation :D

@tracykteal yeah I think that fits the purpose having an etherpad that is easily findable/searchable/accessible and that people can contribute too, sounds good to me!

I've came across thread discussion https://github.com/carpentries/conversations/issues/18 sometime ago, cool resources indeed! However the issue is closed, would be good to add those links to out community resources :D

**Comment by tobyhodges** [comment]
We can talk about this at the mentoring committee meeting tomorrow, which I hope will encourage contributions from the folks there. @orchid00 could you set up an etherpad please?

**Comment by maneesha** [comment]
Thanks for this discussion @tobyhodges  and @orchid00 
Let me know what updates you think would benefit having in the handbook.

**Comment by fmichonneau** [comment]
removing my assignment as I'll leave it to @tobyhodges and @orchid00 to decide with @maneesha whether/how to include this etherpad into the handbook.

**Comment by maneesha** [comment]
Closing this per https://github.com/carpentries/curriculum-development/issues/18
