### ISSUE TITLE
"Edit on github" link does not work for top menu pages

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#192]
If you are on a top menu page like 
- https://docs.carpentries.org/topic_folders/assessment/index.html
- https://docs.carpentries.org/topic_folders/communications/index.html
- https://docs.carpentries.org/topic_folders/instructor_training/index.html
etc.

clicking on "Edit on github" takes you to a page that just says "Not found"

Clicking "Edit on github" from any subpage works as expected.

**Comment by jduckles** [comment]
`/tree/` is somehow missing from the links.

**Comment by fmichonneau** [comment]
Looking into it

**Comment by maneesha** [comment]
@fmichonneau   I think we did the same thing at the same time:  01465f1240bd
However looking at the live build (http://docs-src.carpentries.org/index.html) it still does not work.

**Comment by fmichonneau** [comment]
fixed by e9747198d58c5284dd42d66078b90362c38e0cae

**Comment by fmichonneau** [comment]
@maneesha Ha! I didn't see it. It should be fixed now. This might be a bug in the template, but this fix should address it for now.
