### ISSUE TITLE
Change colours to match website?

### ISSUE THREAD

**Issue by weaverbel** [carpentries/handbook#200]
It might be nice to match the Handbook colours to the colours on the new website so things look uniform across our sites.

**Comment by maneesha** [comment]
@weaverbel do you have any recommendations of people who have the skills to do this?

**Comment by ErinBecker** [comment]
@fmichonneau - maybe we could ask the lesson infrastructure group about this (as a one-off, not an ongoing commitment for supporting the handbook).
