### ISSUE TITLE
Redirect support?

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/handbook#205]
From a [quick search](http://www.sphinx-doc.org/en/master/search.html?q=redirect) it doesn't seem that sphinx has a built-in way of handling redirects.

 There is [this workaround](https://tech.signavio.com/2017/managing-sphinx-redirects) but it seems a little hacky to me.

Am I missing something?

@jduckles is there another layer in our infrastructure we could use to do the redirects?

**Comment by jduckles** [comment]
We can add lines to the docs-src.carpentries.org nginx server. 

Nginx [instructions](https://www.digitalocean.com/community/tutorials/how-to-create-temporary-and-permanent-redirects-with-nginx) 

These lines would go inside the server block of: `/etc/nginx/sites-enabled/docs.carpentries.org`

Then run:
```
 service nginx restart
```

**Comment by maneesha** [comment]
@fmichonneau  and @jduckles  are all the redirects fixed now?

**Comment by maneesha** [comment]
(acutally just pinged @fmichonneau  on https://github.com/carpentries/handbook/issues/178)

**Comment by maneesha** [comment]
@fmichonneau and @jduckles are all the redirects fixed now?
Can we close this?

**Comment by fmichonneau** [comment]
unfortunately not. I haven't had time to implement server-side redirects, and probably won't be able to do so in the near future.

**Comment by jduckles** [comment]
They are fixed, it was a problem with the website `_layouts/redirect.html` not using Jekyll variable calls `{{ }}` that weren't in use by the plugin any longer, hence the empty redirects.
