### ISSUE TITLE
communication materials to handbook

### ISSUE THREAD

**Issue by tracykteal** [carpentries/handbook#208]
Could be a good idea to add communication materials to the handbook, under Communications, such as presentations and grant text. I'll add some things that I have.

**Comment by weaverbel** [comment]
What about linking what we have in `carpentries/commons` ?

**Comment by maneesha** [comment]
@tracykteal and @weaverbel Where would you like these communications materials to go?  I'm happy to have the "commons" materials linked to from the handbook as long as we know things will be kept up to date and easy to find.

**Comment by tracykteal** [comment]
Yes, let's link to https://github.com/carpentries/commons. I just did some updates to that repo, and added a link to a Google folder where we and others can put things for presentations.

**Comment by maneesha** [comment]
Carpentries Commons added with 7bbd0584b6b22fff
