### ISSUE TITLE
Add link to google form for submitting blog posts

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/handbook#209]
I thought there was a google form for submitting blog posts, but I couldn't find it. Maybe add a link to it at https://docs.carpentries.org/topic_folders/communications/submit_blog_post.html?

**Comment by weaverbel** [comment]
There are a couple of forms - one for My Favourite Tool and another for generic posts. I will add them.

**Comment by weaverbel** [comment]
Fixed by this PR https://github.com/carpentries/handbook/pull/211
