### ISSUE TITLE
add more zoom troubleshooting

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#217]
Add notes about these issues to Trainers guide: https://carpentries.topicbox.com/groups/trainers/T5d6a03e9b0abc646

**Comment by fmichonneau** [comment]
still useful to add, but the limitation in wayland has been fixed upstream, so in the few months, this issue should resolve itself...

**Comment by ErinBecker** [comment]
Once these tips have been added to the handbook, link that section to the top of the demo Etherpad so that Trainers have easy access.

**Comment by ErinBecker** [comment]
Fixed with https://github.com/carpentries/handbook/pull/224
