### ISSUE TITLE
Email Templates on Hosting/Teaching page

### ISSUE THREAD

**Issue by sheraaron** [carpentries/handbook#225]
There should be a link on the [Hosting/Teaching](https://docs.carpentries.org/topic_folders/hosts_instructors/index.html) a workshop page for the email templates from [Instructors](https://docs.carpentries.org/topic_folders/workshop_administration/email_templates.html#from-instructors-and-hosts). It's not clearly defined that there are templates available and isn't cleat to know to go to Workshop Admin for the email templates.

**Comment by maneesha** [comment]
Good suggestions @sheraaron  
Would you be able to put in PR to add these links in?

**Comment by maneesha** [comment]
fixed with 6e7311acd7dd2bb22d8
