### ISSUE TITLE
Programmatic assessment

### ISSUE THREAD

**Issue by kariljordan** [carpentries/handbook#230]
Are there plans to update the programmatic assessment section of the handbook @maneesha?

**Comment by maneesha** [comment]
Yes @kariljordan  Thanks for the reminder.  I'll be working on this.

**Comment by maneesha** [comment]
Will do this all at once after the next assessment report is published.

**Comment by maneesha** [comment]
Programmatic assessment section now includes link to website (which has links to all the reports).
