### ISSUE TITLE
Restructure "not good starting points for demos"

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#250]
The section on not good starting points for demos ( [repo](https://github.com/carpentries/handbook/blob/master/topic_folders/instructor_training/trainers_guide.md) and [in handbook](https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html#not-good-starting-points-for-demos) ) is difficult to read.  It's mostly what's not good points but for the geospatial lessons it includes what  are good points mixed with what are not good points.  How can we restructure this section to make it easier to read?

**Comment by ErinBecker** [comment]
I've added this to my to-do list. Hoping to get to it later this week or early next.

**Comment by ErinBecker** [comment]
@maneesha  - I'm working on putting this into a table now.
