### ISSUE TITLE
Links to logos somewhere in the handbook?

### ISSUE THREAD

**Issue by sstevens2** [carpentries/handbook#251]
Maybe we could add links to the logos somewhere in the handbook?
I would make a PR but I wasn't really sure where to put this info in the docs, maybe under communications? Opinions on where to put links to logos?

https://github.com/carpentries/logo

**Comment by weaverbel** [comment]
I have written a new page to address this question now: https://github.com/carpentries/handbook/blob/master/topic_folders/communications/logos.md

**Comment by weaverbel** [comment]
Actually I have had to take that down until we get something better that meshes with trademark policy.

**Comment by sstevens2** [comment]
Thanks for looking into this  @weaverbel ! Sounds like it might be complicated?? 

Sorry for the trouble, I needed some icons for a local orientation info presentation I'm putting together and thought others might look in the docs first now too.

**Comment by weaverbel** [comment]
No worries @sstevens2 - it is actually good that you jogged us into action about this as it is something we should have nailed down before.

**Comment by maneesha** [comment]
Saving this for our new communications staff member.  Any feedback in the meantime is welcome.

**Comment by maneesha** [comment]
Should we be revisiting this? @tracykteal  @ErinBecker @serahrono

**Comment by tracykteal** [comment]
Yes, good idea to put all the logos in one place, or at least one landing page linking to all the logos. Should have the ones we use on websites and the ones for stickers, like the hex stickers.

Data Carpentry are here https://github.com/datacarpentry/logos
Software Carpentry are here https://github.com/swcarpentry/communications/tree/master/misc/logo

I'm not sure if Library Carpentry logos are in a repo yet. @libcce would know.

**Comment by libcce** [comment]
Here is the LC style guide where you can find the logos (the red hex logo) https://github.com/LibraryCarpentry/lc-styleguide

**Comment by fmichonneau** [comment]
:+1: on consolidating all our logo and branding guidelines in a single repo (and also use consistent file names :smile:). The Carpentries hex stickers are in the carpentries/logo repo.

**Comment by maneesha** [comment]
Per @elizabethwilliams8   licensing for all logos is not yet confirmed/approved, so this issue is being tabled.

**Comment by maneesha** [comment]
@serahrono  approved having logos linked in the handbook so this issue can be closed
67ce17d265793736e7a191f3147f8fc0ff5acc5c
