### ISSUE TITLE
Add style guide to Communications section

### ISSUE THREAD

**Issue by tracykteal** [carpentries/handbook#258]
We have a draft style guide https://docs.google.com/document/d/10KutjajR-5RJfPAF8UQlxzcd8tx4PNFXH0acDFD2dBs/edit. When we create the shortened version, it can be added to the handbook.

**Comment by tkphd** [comment]
The linked draft is not publicly accessible (it says, "Access Denied" to me).
Has there been, or will there be, a public request for comments?

**Comment by maneesha** [comment]
This document access is limited to Carpentries staff and a few community members.  I don't want to open up public access without verifying with @weaverbel  that it is ready for public review.  Belinda - can you verify and change permissions accordingly?

**Comment by jduckles** [comment]
Talked to @weaverbel should be good to go, link above is should be open for anyone to make comments.

**Comment by weaverbel** [comment]
I propose I break the guide up into style for referring to Carpentries and lessons and all that and then the grammar and syntax for writing can go in a separate document, possibly incorporating the writing tips I already developed separately. Thoughts?

**Comment by tkphd** [comment]
@jduckles, the [link](https://docs.google.com/document/d/10KutjajR-5RJfPAF8UQlxzcd8tx4PNFXH0acDFD2dBs/edit) still returns "Access Denied" for me.

**Comment by weaverbel** [comment]
Ok the style guide has now shrunk to 7 pages and is really trying to cover just the stuff people need to know to reference us etc. What else is needed?

**Comment by tkphd** [comment]
Under **Q / quotation marks**,
> For parentheses inside direct quotes, always use square brackets.

Under **S / square brackets**,
> In text, square brackets are used for interpolated words in quotations, e.g., Tracy Teal said: ‘Karthik [Ram] went to New Zealand to address a conference.’

These directives seem to be in conflict. It would help to have a clarifying example for parenthesis inside direct quotes.

**Comment by maneesha** [comment]
Thanks all for the feedback above.  Since our communications staff is transitioning I'd like to hold off on doing anything with this until we have a new communications staff member in place.  Additional feedback in the meantime is welcome.

**Comment by rgaiacs** [comment]
> We have a draft style guide https://docs.google.com/document/d/10KutjajR-5RJfPAF8UQlxzcd8tx4PNFXH0acDFD2dBs/edit.

It looks great!

> We will adhere to a similar style  on our website and in other material we make widely available such as blog posts, but not necessarily in lessons.

Why do not use in the English lessons? I believe is better to enforce it across lessons so that all lessons use "capital letters and capitalisation" in the same way instead of have two or more styles in the same episode.

> When we create the shortened version, it can be added to the handbook.

I think the version is short enough to be included in the handbook.

**Comment by maneesha** [comment]
Should we be revisiting this issue?  @tracykteal @ErinBecker @serahrono

**Comment by tracykteal** [comment]
I don't think we have that shortened version yet, and it's not a current project to create that. So, probably something to revisit in a bit. Good to re-up so it's on the community team's radar.

**Comment by karenword** [comment]
I've gotten a request to have the style guide available in the handbook. Bumping this issue in case it's ready to move! :)

**Comment by maneesha** [comment]
Tagging @serahrono  for consideration.

**Comment by serahrono** [comment]
Thanks @maneesha and hi @karenword,

We haven't had time to update the Style Guide in Q1, but I've given it some thought and I think we should add the first version that @weaverbel put together to our handbook, and any updates we make to it over time can be added to the handbook as revisions. What do you think? cc @tracykteal @ErinBecker @kariljordan ?

**Comment by kariljordan** [comment]
I'm on board with this. @weaverbel did a phenomenal job on the style guide, and updating/revising it is not within our current project scope. Let's have @serahrono add the current version to the handbook as version one and give @weaverbel the credit she deserves (hi Belinda!), and in the future we can revisit making revisions.

**Comment by tracykteal** [comment]
+1 to including what @weaverbel put together. One thing people want to know is how to use 'The Carpentries' versus 'Carpentries'. Maybe we could put that at the top of the document as well as in the 'C' section, to make it slightly more available.

**Comment by maneesha** [comment]
Fixed with f66dc2011f12de6eed74ac224642c449fb1bd2ab
