### ISSUE TITLE
email templates missing

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#27]
Not all of these are in the docs yet: https://docs.google.com/document/d/19JQPRU1IIlHZqaiVfC7ecD0U3SYgzlfpXszQ0UqyFIk/edit

**Comment by maneesha** [comment]
@ErinBecker  I think they are all there now (the templates, not the scripts).
Let me know if you see anything missing.

**Comment by ErinBecker** [comment]
Great, thanks @maneesha. It looks like they are all there now.
