### ISSUE TITLE
Etherpad - permanent? (likely not)

### ISSUE THREAD

**Issue by gitti1** [carpentries/handbook#284]
Hi all, 

a small thing, it may be good to add a warning at the point of creation that the Etherpad will not be permanently hosted. 

All the best, 
Birgit

**Comment by maneesha** [comment]
@gitti1   Etherpads are sort of permanent... Ideally they stay up as long as The Carpentries maintains the server. Things do sometimes break though, but that's the exception, not the rule.  

Do you have suggestions -- or was there a time that the etherpad's longevity didn't meet expectations?

**Comment by maneesha** [comment]
@gitti1  Checking in again - let me know if you have suggestions based on your experience using etherpads.

**Comment by maneesha** [comment]
Closing this.  @gitti1   Feel free to re-open if you have additional questions or comments.

**Comment by maneesha** [comment]
Over email @gitti1  asked:
> From our local infrastructure provider I had the experience that they do not store the pads for very long if you do not regularly revisit the pages. As I understand this does not seem an issue with the Carpentries pages if I understand you correctly? 

@jduckles @fmichonneau  You both know more about how etherpads are managed.  Would you be able to answer this question?

**Comment by jduckles** [comment]
For now we keep all pads in perpetuity. This could change in the future, but if it does, we'll amend the notice on all pads newly created to set this expectation. Our default guidance is to treat pads as ephemeral and not to be trusted as an archival place for data or information. Pads can be easily exported with `/export/txt` or `export/html` appended to the end of the pad name (i.e. https://pad.carpentries.org/trainers/export/html ). This can even be scripted if you'd like to keep an archive of a pad and its changes over time.

**Comment by maneesha** [comment]
Thanks @jduckles 
Closing this again.  @gitti1 Please feel free to re-open if you still have questions about this.
