### ISSUE TITLE
What copyright/license should this have?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#30]
The default footer line looks like:
© Copyright 2018, The Carpentries.

Should we have a different license like cc?  
Can we attribute it just to Carpentries or does CI need to be acknowledged?

**Comment by maneesha** [comment]
@tracykteal @ErinBecker  any suggestions?  I could do CC-BY 4.0 (the most recent version) but first I'd want to understand why for lessons, DC uses CC-BY 2.0 while SWC uses CC-BY 4.0.  Are there any salient differences?

**Comment by tracykteal** [comment]
4.0 updates https://creativecommons.org/share-your-work/licensing-considerations/version4/

We should use CC-BY 4.0 or CC0 if we don't care about attribution.

**Comment by maneesha** [comment]
CC-BY 4.0 made most sense to me (that's what SWC and instructor training use) but I'm curious to know if there are any significant differences that caused DC to stick with 2.0.  I haven't read all the fine print :-).

**Comment by tracykteal** [comment]
CI holds the Software and Data Carpentry trademarks, so they should be mentioned in the trademark section.

**Comment by maneesha** [comment]
Need to look into this.   Need to change the word copyright, not just the following text.
In conf.py changing 

copyright = '2018, The Carpentries'  to copyright = '2018, The Carpentries under CC BY 4.0' still makes it use the word "copyright" on the site.

**Comment by tracykteal** [comment]
You can use for this the same license we're using in the lessons. @fmichonneau would be able to talk about the one in the lesson templates

**Comment by fmichonneau** [comment]
There is no good reason to use CC-BY 2.0. I think where you saw 2.0 meant that the lesson hadn't updated the template in a long time. I'll work on updating the templates across DC lessons.

I think it's OK to have the word "copyright" when using a CC-BY license. It signals how the attribution should be listed.

**Comment by maneesha** [comment]
Thanks @fmichonneau 
The footer now reads:

> © Copyright Released under CC-BY 4.0 License.

I can't get that to appear as a hyperlink.  Should there be more information in the "About" section of this site?

**Comment by fmichonneau** [comment]
Looking around at other people are doing it, I recommend the footer to read:

> Copyright: (C) 2018, The Carpentries. This content is released under the terms of the Creative Commons Attribution License. 

I think it's a good idea to include a longer version in the "About" section or in a "License" section.

**Comment by maneesha** [comment]
Footer has been fixed with abff3fb 
Leaving this open to add a longer version in the About --> License section.

**Comment by maneesha** [comment]
LIcense was added here: https://docs.carpentries.org/LICENSE.html
