### ISSUE TITLE
What order should sidebar categories go in?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#31]
For no particular reason right now it goes:
General ->  Maintainers, Communication, Workshop Admin, Instructor Training, Policies.
Staff -> Memberships, Finance

Is there any logical order that would serve us better?

**Comment by tobyhodges** [comment]
This seems like a sensible approach to me. Within these two domains, you could try to order the categories from widest relevance down to narrowest i.e. the stuff that the most people will be interested in at the top, the 'niche' stuff, for only one or two people, near the bottom.

To my mind, that suggests the following:

Communication
Maintainers
Mentoring
Instructor Training
Workshop Admin
Policies

But happy to be overruled by someone with more experience!

**Comment by ErinBecker** [comment]
imho "Maintainers" should be "Lesson Maintenance"

**Comment by maneesha** [comment]
Fixed with 4829725
Alphabetical order for now.
Can reopen issue if someone has other ideas.
