### ISSUE TITLE
New changes not building

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#311]
1e99ff7 and 9a1ee28  are not building on the [preview site](http://docs.carpentries.org.s3-website-us-east-1.amazonaws.com/topic_folders/workshop_administration/survey_monkey.html) or the [live site](https://docs.carpentries.org/).

Maybe @fmichonneau  or @jduckles can help?

**Comment by maneesha** [comment]
No new changes are building to the preview site or the live site.

**Comment by jduckles** [comment]
Fixed, seemed to be someone logged in and manually built as `root` user causing a permissions problem on the `_build` directory. In the future, if manually building, please build as `data` user.

**Comment by maneesha** [comment]
[Commits made yesterday](https://github.com/carpentries/handbook/commits/master) are not appearing on the live site [live site](https://docs.carpentries.org/).
They do appear on the  [preview site](http://docs.carpentries.org.s3-website-us-east-1.amazonaws.com/).

**Comment by fmichonneau** [comment]
They are showing up for me on the live site. If the changes appear on the preview site, they will eventually make it to the live site. We can force the cache update but it costs money and we should do it only when the updates are time sensitive.
