### ISSUE TITLE
Update email requesting logistics from host

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#316]
Now that we have a more comprehensive workshop request form, we should ask that hosts just use this form, rather than having to send another email to get all this logistical information.

So this email template  (https://github.com/carpentries/handbook/blob/master/topic_folders/workshop_administration/email_templates.md#logistics-information-from-host)
can be updated to say something like "Thanks for requesting a workshop, please fill in this form so we have all the information we need to get started planning."

@sheraaron  What do you think?

**Comment by sheraaron** [comment]
@maneesha yes. That is what I am doing now.

**Comment by maneesha** [comment]
Hi @sheraaron   This may have fallen through the cracks, so I updated it here. Feel free to re-open this if you want to make any other changes.

https://docs.carpentries.org/topic_folders/workshop_administration/email_templates.html?highlight=logistics#logistics-information-from-host
