### ISSUE TITLE
How to submit LC blog post

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#317]
@libcce 
We have instructions here (https://github.com/carpentries/handbook/blob/master/topic_folders/communications/submit_blog_post.md) on how to format blog posts to be submitted to the DC or SWC websites or the Carpentries site.  I believe we have different sets of instructions because the two websites build differently. 

I don't know how the LC site works.  It would be great if you could put in a PR for how to format blog posts for the LC site.

**Comment by libcce** [comment]
Thanks @maneesha for catching this. FYI, LC uses The Carpentries website template. I've submitted a PR https://github.com/carpentries/handbook/pull/320 to add the LC blog post information.

**Comment by maneesha** [comment]
PR #320 has been merged
