### ISSUE TITLE
Include LC in mentoring groups?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#318]
@kariljordan 
This page (https://github.com/carpentries/handbook/blob/master/topic_folders/instructor_development/mentoring_groups.md#requirements) notes that people must be "either a newly certified Software or Data Carpentry instructor or be in the process of completing certification. Generally Mentees will have taught one or no workshops, but may have been helpers before."

Do you want to include LC in this?

**Comment by maneesha** [comment]
We can have it say "...either a newly certified Carpentries instructor or be in the process of completing certification. Generally Mentees will have taught one or no workshops, but may have been helpers before."

The goal has been to limit how much we refer to specific Carpentries lesson programs (unless it's necessary).  I don't think we need explicit feedback from @libcce  -- I just wanted to check with @kariljordan  as the manager of the mentoring groups.

**Comment by kariljordan** [comment]
Oh! I totally missed that. I missed that it said DC and SWC and I was focused on the other language. Yes! I love that recommendation. I'll submit a PR.

**Comment by libcce** [comment]
+1 to what @maneesha just wrote https://github.com/carpentries/handbook/issues/318#issuecomment-446331132 This is just one of the many changes that we need to make to the language from referring to individual Lesson Programs to mentioning The Carpentries.

**Comment by maneesha** [comment]
Fixed with #319
