### ISSUE TITLE
Need to add table for Staff Expenses section

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#33]
The original document from @elizabethwilliams8 includes a table of expense categories. I'm  still trying to figure out how to style tables so I have not included the table here.

https://docs.google.com/document/d/10HMG_0ZNklXINpbXBr6hNfEUzS0Uc7M4MCqjVm5zSYs/edit

**Comment by tobyhodges** [comment]
Wow that's a big table. Recreating this in raw HTML would be painful, so my suggestion in #9 isn't such a good one...

**Comment by maneesha** [comment]
Yeah, if I can't figure out how to render tables, I may end up keeping just this table as an external link. 
@tobyhodges suggestion may work for a smaller table.

**Comment by maneesha** [comment]
Closing this as we never incorporated the staff resources section. May revisit this at some point with @Talishask  and @elizabethwilliams8
