### ISSUE TITLE
Project Organization and Management for Genomics for teaching demos?

### ISSUE THREAD

**Issue by dvanic** [carpentries/handbook#337]
I've had a trainee suggest "Project Organization and Management for Genomics" as a lesson for the teaching checkout - but I just had a look through the content, and there is no live coding in this lesson!

Should it be removed from possible use from teaching demos completely???

[Link TBA](https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html#starting-points-for-demos)

**Comment by maneesha** [comment]
Thanks for raising this question @dvanic 
I think @ErinBecker  knows this lesson best so she may be able to respond here.

**Comment by maneesha** [comment]
pinging @ErinBecker

**Comment by ErinBecker** [comment]
Thanks for the question @dvanic and sorry for the delayed response. The Genomics lessons have been very challenging to use for teaching demos for a couple of reasons. 
- The Project Organization lesson as you mentioned doesn't have any live coding. 
- The Shell lesson relies on a large (50 Gb) dataset.
- The Wrangling lesson requires both the large dataset, and a rather complicated set of software installations.

For the actual workshops, learners and Instructors use a remote copy of the data and software (usually through AWS), and so don't need to worry about storage space and troubleshooting all of the software installation locally. However, if Instructors are going to use these lessons for their teaching demo, they would need to have access to the data (for the shell lesson and wrangling lesson) and to the software (for the wrangling lesson). 

I'm currently working with a trainee who wants to use the Genomics wrangling lesson for her teaching demo (@janu123) to see what the best resolution is in terms of making it possible for Instructors to demo with these materials without burdening them with storage or software issues. She's scheduling a meeting with me later this month to work through some issues. I'm happy to invite you to the call if it's at a time that is convenient for you (and if you're interested in joining!), but also happy to report back afterwards. In the meantime, we are not allowing/supporting Genomics demos. 

I'd be happy for any suggestions about how best to document that so there's no confusion with trainees showing up at a demo to do Genomics. Any ideas?

**Comment by ErinBecker** [comment]
After a quick look at the [teaching demos Etherpad](https://pad.carpentries.org/teaching-demos-recovered), I see at least 4 people signed up to use the Genomics lessons. The next is on the 22nd. I'll bump this up my priority list. Suggestions welcome!

**Comment by ErinBecker** [comment]
Thanks to @taylorreiter we now have a possible solution for this issue. Taylor pointed out that the dataset for the [Introduction to Command Line for Genomics](https://datacarpentry.org/shell-genomics/) lesson is only in the Mb range. Trainees can download that data from Figshare (I'm working on getting the updated version to our Figshare account now and will update the links in the lesson) and use it in a teaching demo. That lesson doesn't require any specialized software (unlike the [Data Wrangling](https://datacarpentry.org/wrangling-genomics/) lesson, which requires a Gb scale dataset and several specialized software programs. I think we'll be able to accomodate trainees doing teaching demos from the shell lesson and the (newly updated - thanks again @taylorreiter!) Project Organization lesson. Now I just need to figure out where to make that information available for both trainees and Trainers. I'll start compiling a list of places, including the Trainers section of the Handbook and the Genomics lesson page, but please let me know if you have any suggestions about other places we need to communicate that information. Looking forward to getting this solution in place!

**Comment by maneesha** [comment]
@ErinBecker  Checking in on the progress of this.

**Comment by ErinBecker** [comment]
Thanks for checking @maneesha. Resolving this issue is part of the larger conversation that we've been having about the Genomics Curriculum Relaunch project. As part of that project, I've put together a set of [detailed instructions](https://docs.google.com/document/d/1bj5N022o4sTR8kBIiG0aVCHZzyJLkzR3q9Jraw75i2s/edit) for trainees and Trainers about appropriate starting points in the Genomics lessons. This document is publically viewable, but is not in its final / stable form yet. This documentation will be live and public by 25 April, but if anyone following this issue would like to go to the Google doc and leave comments and suggestions, that would also be greatly appreciated.

**Comment by maneesha** [comment]
Closing this as we have an updated set of starting points for Trainers (https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html#starting-points-for-demos) and instructions for trainees (https://datacarpentry.org/genomics-workshop/teaching_demos/index.html, accessible at https://datacarpentry.org/genomics-workshop/ >> "Extras"
