### ISSUE TITLE
broken link to AMY login

### ISSUE THREAD

**Issue by pitviper6** [carpentries/handbook#343]

**Comment by pitviper6** [comment]
The link to the AMY login page is broken in the AMY manual:
Logging in
Log in to AMY here. Contact Carpentries staff if you need login credentials.

Broken link:
https://amy.software-carpentry.org/workshops/admin-dashboard/

**Comment by maneesha** [comment]
This is being fixed.  Closing as it's a duplicate of https://github.com/swcarpentry/amy/issues/1423

**Comment by pitviper6** [comment]
Oh geez, I'm sorry! I even went through the issues to make sure I wasn't duplicating anything and missed that.
