### ISSUE TITLE
include section on dealing with  unexpected or emergency situations 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#355]
We should have an easy to follow guide on suggested things to do when unexpected or emergency situations come up.

Example situations:

* Co-instructor can't come due to illness, flight delay, etc.
* Group can't get on wi-fi

Other examples?  @sheraaron

**Comment by maneesha** [comment]
@sheraaronhurt Do you think we should include a separate section for this, or do you think it gets covered in all the other workshop admin information?

**Comment by sheraaronhurt** [comment]
@maneesha  this would be a good section to add. We cover a lot of information and I don't want this to get lost. It would be good for these to be stand alones. At the moment I can't think of any other emergency situations but I will poll the RC's to see if they have any.

**Comment by maneesha** [comment]
Thanks @sheraaronhurt.  I have started to list out what you might do for some of these situations.  Please continue to add here.  Once we have a fair amount of content, I'll move it to the handbook - and we can always add more there later.


**Situation: Co-instructor can't come due to illness, flight delay, etc.** 
* Contact team@carpentries.org.  Depending on how much notice we get, we may be able to help find another Instructor.
* Contact your helpers and host to see if any of them can provide extra support, and even teach a portion of the lessons
* If your co-Instructor is delayed (rather than having to cancel entirely), adjust the schedule of your event so that person's lesson come later in the event.

**Situation: Group can't get on wi-fi**
* If you anticipate this in advance, come with a handful of thumb drives to install software and data files
* If only some learners can get on wifi, consider pairing them up so they can follow on the connected person's machine

**Comment by sheraaronhurt** [comment]
@maneesha  this is great! I will report back once I meet with the RC's

**Comment by sheraaronhurt** [comment]
@maneesha  not having access to the building came up as an emergency

**Comment by maneesha** [comment]
Thanks @sheraaronhurt 
What would we suggest Instructors do in that case?

**Comment by sheraaronhurt** [comment]
@maneesha be sure to have the contact number for the host(s) prior to the workshop and any other persons involved with the logistics onsite. If the building isn't available be sure to contact all of the participants letting the know the workshop has been cancelled until further notice. 

Feel free to add to this.

**Comment by maneesha** [comment]
Fixed with 01aeb1be65eafd0b8622d61be115b91db03eaea0  and
b94de29e86e446613d1b5c4ca3680d740bb816d7
