### ISSUE TITLE
clarify workshop fees for self-organized workshops

### ISSUE THREAD

**Issue by kcranston** [carpentries/handbook#359]
In the [workshop checklists](https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html) we mention workshop fees multiple time (specifically [here in the checklist](https://github.com/carpentries/handbook/blob/afa14a4e8297bb30786fa6901af86f15c5eea852/topic_folders/hosts_instructors/hosts_instructors_checklist.md#L17) and in the [billing guidelines](https://github.com/carpentries/handbook/blob/afa14a4e8297bb30786fa6901af86f15c5eea852/topic_folders/hosts_instructors/hosts_instructors_checklist.md#L36)). We should clarify that the fees only apply to centrally-organized workshops, not self-organized. 

This came up in a recent instructor training, where trainees were confused about the wording in the handbook vs what is on the [workshop request form](https://amy.software-carpentry.org/forms/workshop/) for self-organized.

**Comment by maneesha** [comment]
Thanks for this @kcranston 
We'll look across our various forms, checklists, etc. to be sure our messaging is consistent.
