### ISSUE TITLE
Additional sections to be added

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#36]
* Mentorship
* Assessment

Anything else?

**Comment by maneesha** [comment]
@kariljordan  I've added a mentorship section and am emailing you about getting feedback on that.
Is there anything assessment related that should go in this handbook?

**Comment by kariljordan** [comment]
Yes, we can add info about the assessment network, learner assessment, and instructor assessment. Should I submit a PR? I think I was supposed to do this already...but please remind me of the process and I'll get it done.

**Comment by maneesha** [comment]
@kariljordan       Any documentation you already have please put in the `drafts` folder of this repo.  I'll take care of everything from there.

**Comment by kariljordan** [comment]
I added the 3 drafts! All set with this issue from my standpoint.

**Comment by maneesha** [comment]
Assessment added with 3007ffe73 and bb38b249
