### ISSUE TITLE
trainers guide documentation is duplicated

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#361]
This documentation appears here https://carpentries.github.io/instructor-training/guide/index.html 
  and  here https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html#trainer-checklists.

Needs to be consolidated.

**Comment by maneesha** [comment]
@karenword  and @ChristinaLK   Since you two maintain the content on the instructor training site, do you have a preference as to whether this should be in the IT curriculum materials or in the handbook?

**Comment by karenword** [comment]
Once the handbook copied everything that was in the Instructor Notes, we modified the Instructor notes to be more customized to the process of actually teaching the curriculum. In this process we deleted much of the material that was duplicated in the handbook, but chose to leave some of that material with the idea that Trainers might reasonably look there to find this information. 

Maintenance is the main problem with duplicating material — when we update one and not another, that creates problems. So maybe the things that are still in the Instructor Notes should remain only there? I’m not confident about that, however.
@ChristinaLK?

**Comment by maneesha** [comment]
I agree we should not have duplicated information because it is difficult to keep up with maintaining and updating it.  Right now what's in the handbook and what's in the IT materials is *mostly* the same.  I say mostly because they are maintained separately.  I would highly recommend removing it from either the handbook or the IT materials, and linking to the other source.  

I have no strong preference whether it should live in IT guide or handbook.

**Comment by maneesha** [comment]
Hi @karenword I think we now have the Trainers Guide just in the IT curriculum so I am closing this.  Feel free to re-open if you see anything else that is duplicated.
