### ISSUE TITLE
Add link to Google template for instructor training

### ISSUE THREAD

**Issue by amyehodge** [carpentries/handbook#362]
Add the link to the Google template (https://docs.google.com/document/d/1P_w1rgdVk4SpXvILSS-ZKz8Ujqklfujpc_zHf8D-G1A/edit?usp=sharing) to the handbook on page https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html#trainer-checklists

**Comment by maneesha** [comment]
Do we  need to edit this before incorporating it in the handbook?  The top says 
> Please note: this document is not currently maintained along with the other Instructor Training materials. Please check curriculum for updates prior to use.

Pinging @karenword @ChristinaLK

**Comment by karenword** [comment]
This statement is true -- Trainers want to have this document (and be able to find it) but we haven't committed to keeping it updated as part of the Maintainer role. It is up to those who use the document to be sure it is updated. 

It should still probably be linked from the handbook, with that disclaimer intact. Is that ok?

**Comment by maneesha** [comment]
Done.
