### ISSUE TITLE
Tracking Trainee Checkout section Tracking Lesson Contribution

### ISSUE THREAD

**Issue by k8hertweck** [carpentries/handbook#366]
This section has language duplicated from Tracking Discussion Attendance. I'm fairly certain this is a quick fix and can submit a PR but want to make sure it isn't a substantially different workflow from the other sections?

**Comment by maneesha** [comment]
Hi @k8hertweck  Can you link to the specific sections you see duplicated?

**Comment by maneesha** [comment]
Pinging @k8hertweck

**Comment by maneesha** [comment]
Closing this now.  @k8hertweck  please feel free to re-open if there is something that should be fixed.
