### ISSUE TITLE
.md extensions are getting stripped and links are breaking

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#372]
See for example 
https://github.com/carpentries/handbook/issues/365

**Comment by maneesha** [comment]
Also as reported by @karenword  

> So apparently the scoring rubric link in the handbook from the page I tweeted earlier today isn’t working. But the reason why I’m posting it here is because I don’t understand why. The link address renders properly on the github version of the page here: https://github.com/carpentries/handbook/blob/master/topic_folders/for_instructors/new_instructors.md but does not on the handbook-rendered version of the page here: https://docs.carpentries.org/topic_folders/for_instructors/new_instructors.html

**Comment by maneesha** [comment]
Still need to figure out how/why this is happening.  From @fmichonneau  a few weeks ago:

> I spent quite a bit of time earlier this week investigating something similar. I think it's a bug with Sphynx. It looks like the `.md` extensions get stripped during the rendering process. It didn't do it locally at first but I upgraded my installation in the process of trying to figure it out, and then it started to do it.

**Comment by katrinleinweber** [comment]
This [SO post seems similar to our issue & contains an upvoted solution](https://stackoverflow.com/questions/52429549/sphinx-documentation-and-links-to-markdown).

**Comment by maneesha** [comment]
Thanks @katrinleinweber 
I'll look into this more.

**Comment by maneesha** [comment]
As a temporary hack I've added anchor tags to the `.md` extensions.  I'll look in the possible solution Katrin shared at another time.

**Comment by maneesha** [comment]
See https://github.com/carpentries/handbook/pull/476
and 
https://github.com/carpentries/handbook/pull/475

**Comment by maneesha** [comment]
Looking at the SO post shared above, it looks like AutoStructify actually transforms `*.md` to `*.html` which is not what we want -- we need to have the original `.md` preserved.  Closing this as the hacky approach seems to work for now.
