### ISSUE TITLE
feature request: link The Carpentries homepage to the logo

### ISSUE THREAD

**Issue by raynamharris** [carpentries/handbook#386]
I'm wondering if it is possible to add a hyperlink to the logo in the top left-hand corner that links to The Carpentries home page? As far as I can tell, there aren't any links to the main website, and I find that I always want one. The logo seems like a good thing to hyperlink, but I'm open to other suggestions.

**Comment by maneesha** [comment]
@raynamharris  This is a good suggestion.  At some point I'll poke around and see what the best way to do this would be.

**Comment by maneesha** [comment]
I haven't found a way to hyperlink the logo but I have added general introductory information to the front page with 844e773578b38e961f043c78cd6c019624df1fb8
