### ISSUE TITLE
link to scripts for email templates when available

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#39]
Some of the email templates for instructor training (http://docs.carpentries.org/topic_folders/instructor_training/email_templates.html)
note that they have been migrated to a script.  They should then link to the script file being used.

**Comment by ErinBecker** [comment]
1) Update the "this has been migrated to a script" text to say "This email is usually sent with a script. The canonical version of the text is the version below."

2) Clean up scripts to remove api links and add instructions for formatting csv files (which columns are needed). 

3) Add scripts to a folder in the handbook repo.

4) Add links to scripts to documentation.

**Comment by ErinBecker** [comment]
2-4 can be done after the initial handbook release.

**Comment by maneesha** [comment]
Item 1 is done with a29d0b3

**Comment by maneesha** [comment]
Closing as stale -feel free to re-open if needed.
