### ISSUE TITLE
Maintainers application - should responses be public?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#40]
The Maintainers section includes link to application to be a maintainer.  The responses to this application are publicly visible even when not logged in to any Google account. 
Is this intentional?

**Comment by ErinBecker** [comment]
That is definitely not intentional. Please change the link to this one: https://docs.google.com/forms/d/e/1FAIpQLSfuSUffza_DrqqMwdokdNtSgNfdxzMSmbwLw8655GU31BXPyg/viewform

**Comment by maneesha** [comment]
@ErinBecker 
I am changing the link to the application.  Can you give me access to edit the application itself?  It includes a link to the maintainers guide google doc which we are deprecating in favor of this new handbook.

**Comment by ErinBecker** [comment]
Thanks @maneesha - I sent you the edit link in Slack and changed the link within the application to http://docs.carpentries.org/topic_folders/maintainers/maintainers.html.

**Comment by maneesha** [comment]
Fixed with d99c78f
