### ISSUE TITLE
Put CoC information in its own section (not buried in "Policies")

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#400]
We currently have all the  Code of Conduct information buried in the "Policies" section.  I'd like to try moving this to its own section and have it at the very top of the left side menu to make it easier to find.

(@kariljordan   This issue is for a reminder to myself to try some things out.  Nothing is changing now so there's nothing you need to do now.  I will share some ideas when I have time to put things together.)

**Comment by kariljordan** [comment]
@maneesha thank you! I love the idea btw.

**Comment by maneesha** [comment]
Fixed with 8ebd6016cf73de008b71d6698f66f533df1dcf13 
7a0272d24e95211f6a9b5d4522709e6dae466c21
740f70efebf43ba7116cfd39d1bab22ef88193a8
3de4775f9ef87e2c9eba646edafc80c95764b08f
