### ISSUE TITLE
Code of Conduct document in handbook is out of date

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#41]
See https://github.com/carpentries/usersguides/blob/9e626b9ea8fbc3f23388d176904a1130af3db006/topic_folders/policies/CoC-reporting.md

**Comment by ErinBecker** [comment]
Currently there are multiple "canonical" places where the CoC lives - the DC website, the SWC website (and soon the Carpentries website and the Library Carpentry website). The CoC pages on the websites should all link directly to the CoC page in the Handbook and not be duplicated text. This will ensure that any updates to the text are consistently shown in all locations.

**Comment by ErinBecker** [comment]
Before deprecating the website versions - the CoC in this handbook needs to be updated based on changes to the website(s).

**Comment by maneesha** [comment]
It looks like what is here: http://www.datacarpentry.org/code-of-conduct/
and here: https://software-carpentry.org/conduct/ 
is the same 
so will update http://docs.carpentries.org/topic_folders/policies/code-of-conduct.html to be the same.  I think anything else should "wait" as we are making other changes as referenced in #7

**Comment by ErinBecker** [comment]
@maneesha - I'm currently working on puting in a PR for this.
