### ISSUE TITLE
SocialSci Spreadsheets lesson for teaching demos

### ISSUE THREAD

**Issue by sstevens2** [carpentries/handbook#412]
Hi!  I hosted a teaching demo today and while the handbook says you can start from any episode, I did not find that to be the case.  I had them start from the 2nd episode and it doesn't have any live coding (at least in the first 5 min) and that was a bit tough for the trainee.  They still did a great job though.

https://datacarpentry.org/spreadsheets-socialsci/

They did say that the only episodes in this lesson they thought would be good to start from were the ' data as dates' and the 'quality assurance' episodes.  I can make a PR noting that in the table later this week if you think it is a good change to make. Let me know.

Thanks,
Sarah

**Comment by maneesha** [comment]
Thanks for bringing this up @sstevens2 
We can adjust the table when issue #411 is resolved.

**Comment by maneesha** [comment]
Thanks @sstevens2 
I just assigned this to myself but then saw you had also offered to put in a PR.  I'd welcome this if you are still interested in doing it.

**Comment by maneesha** [comment]
Fixed with #420
