### ISSUE TITLE
How to enable popup in sidebar footer

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#42]
This site uses the Read the Docs Sphinx theme.  On that theme's own page (and other sites built on that theme) the footer in the side bar has a popup to to to other versions, to go to github, etc.

Example: https://sphinx-rtd-theme.readthedocs.io/en/latest/

I can't figure out how to enable this popup.

**Comment by maneesha** [comment]
@jduckles  you're usually good at figuring out things like this. Can you help?

**Comment by jduckles** [comment]
Looks like its related to an as-yet unmerged patch: https://github.com/rtfd/sphinx_rtd_theme/pull/574

**Comment by tobyhodges** [comment]
That PR has since been closed

**Comment by maneesha** [comment]
Low priority as we have the "Edit on github" link on top and we aren't dealing with versions.  Might be nice to look into more later.

**Comment by maneesha** [comment]
Don't think we need this - closing.
