### ISSUE TITLE
foreign words example not italicised

### ISSUE THREAD

**Issue by amyehodge** [carpentries/handbook#441]
In the following excerpt, "bête noire" should be italicized, I believe.

foreign words and phrases
Italicise these and provide accents where applicable, _e.g._, bête noire. In the case of frequently used foreign terms in accepted English usage, _e.g._, avant garde, vis a vis, vice versa, you do not need to italicise.

**Comment by serahrono** [comment]
great catch @amyehodge! Thank you!
