### ISSUE TITLE
Guide to PRs on Carpentries lessons

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#451]
See https://github.com/dmgt/swc_github_flow/blob/master/for_novice_contributors.md

This should go in handbook and be referenced by  lesson_example, CONTRIBUTING.md and Instructor Training.

**Comment by dmgt** [comment]
Thanks! This guide was a joint effort together with @dtwrub and @daisieh

I remember finding the instructions in CONTRIBUTING.md cryptic for newcomers if you didn't already know what  the `gh-pages` branch was and how to set yourself up with forking and branching, so agree it'd be helpful to add something there. Right now the "How to contribute" and "Using Github" sections have "If you are comfortable using git" and "If you don't know how to use GitHub", but not, for example, "If you are looking for step-by-step instructions on how to edit lesson materials on GitHub (suitable for learners who have completed the git lesson)..." 

Also, is there a standard format to cite the handbook? I see it's CC-BY 4.0, it doesn't appear to have a CITATION.md file, so I was wondering if this is a deliberate choice or if it would be worth considering adding one

**Comment by maneesha** [comment]
Guide added with 2dd3030d9de475e3143394e887df66a9952f3c59

**Comment by maneesha** [comment]
Closing this here. Opened issue in [lesson-example](https://github.com/carpentries/lesson-example/issues/262) to incorporate this there.
