### ISSUE TITLE
Renames Carpentries en Latinoamerica?

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#452]
@raynamharris  made updates to the Carpentries website (https://github.com/carpentries/carpentries.org/pull/447) updating how we refer to Carpentries en Latinoamerica.  

@raynamharris Would you recommend similar changes here?
https://docs.carpentries.org/topic_folders/regional_communities/carpentries_en_latinoamerica.html

**Comment by maneesha** [comment]
If it's as simple as moving things around, I can do this but I want to be sure any language changes go by a fluent speaker.

**Comment by raynamharris** [comment]
Yes, a simple rename would be great. A few of us are working to revamp it can add more substantial updates later in time.

**Comment by maneesha** [comment]
Fixed with 86b4cb4616023bd7e08f70792698939b45f21482
