### ISSUE TITLE
"Teaching unofficial Carpentries workshops" page needs links

### ISSUE THREAD

**Issue by katrinleinweber** [carpentries/handbook#457]
Good 1st issue / newcomer-friendly:

See https://docs.carpentries.org/topic_folders/hosts_instructors/unofficial_workshops.html. Can be done on https://github.com/carpentries/handbook/edit/master/topic_folders/hosts_instructors/unofficial_workshops.md , but with `[text](https://...)` style or using `{% include links.md %}` or similar? @maneesha

**Comment by maneesha** [comment]
Thanks for bringing this up @katrinleinweber 
Are there specific things you think should be linked from this page?

**Comment by katrinleinweber** [comment]
Only the "Read more" links for now ;-)

**Comment by maneesha** [comment]
Thanks @katrinleinweber  - I missed that!  I'll fix that now.

**Comment by katrinleinweber** [comment]
I already did, see #459 ;-)

**Comment by maneesha** [comment]
Fixed with 9b141e0bf679143d48a42ab8bf2a7adc9628ea83
(I fixed it before I saw #459 -- thanks to @katrinleinweber  for catching this!)
