### ISSUE TITLE
Pad of Pads should be added.

### ISSUE THREAD

**Issue by symulation** [carpentries/handbook#46]
And anything like this.  Perhaps a "General information" category?

**Comment by ErinBecker** [comment]
@symulation - Thanks for this. Yes, the pad of pads would be a good resource to add here. I'm marking this after-release so that we can think about what else goes into a "general information" or "quick links" category.

**Comment by maneesha** [comment]
Fixed with 9585fd932f2ed8f03a9c89f40e2f1963df3eacd7
