### ISSUE TITLE
Meaning of a sentence

### ISSUE THREAD

**Issue by LUS24** [carpentries/handbook#461]
Hi, I'm helping to translate the handbook to Spanish and I'm having trouble with this sentence in the fourth paragraph of the [ Code of Conduct Incident Response Guidelines](https://docs.carpentries.org/topic_folders/policies/incident-response.html) where it says:

"_Ideally, we would all be able to **diffuse** an incident._"

Shouldn't it say **defuse** instead?

Definitions I found:
**Diffuse**: spread over a wide area or between a large number of people.
**Defuse**: make (a situation) less tense or dangerous.

Thanks in advance

Leonardo

**Comment by maneesha** [comment]
I think you're right @LUS24 

@kariljordan  Would you agree?

**Comment by kariljordan** [comment]
@LUS24 you're right! This is such a great catch. Thank you. I'll submit a PR.

**Comment by maneesha** [comment]
Closed with #464 
Thanks @LUS24 !
