### ISSUE TITLE
Checklists: How to increase adherence to them?

### ISSUE THREAD

**Issue by katrinleinweber** [carpentries/handbook#468]
As an instructor I find myself too often discussing basic pre-workshop tasks and their assignment.

a) Maybe our checklists would be easier to follow if they were [numbered](https://about.gitlab.com/handbook/people-operations/group-conversations/#suggestions)? Definitely, that would make refering to specific tasks easier.

b) We could also visualise the task list, e.g. as a [gantt chart](https://mermaidjs.github.io/gantt.html). [More effort](https://github.com/mgaitan/sphinxcontrib-mermaid) than above, but :sunglasses:  and possibly more effective, in case of a "wall of text" effect causing the checklists to be ignored.

**Comment by maneesha** [comment]
Good suggestions @katrinleinweber 

What does @sheraaronhurt  think from a workshop admin perspective?  Do we often find people don't use the checklists?

**Comment by sheraaronhurt** [comment]
@maneesha I have not gotten any feedback either way (being used or not). However, if instructors are using them adn would like them numbered as suggested by @katrinleinweber

**Comment by maneesha** [comment]
Thanks for the feedback @sheraaronhurt 

@katrinleinweber  would you be interested in submitting a PR to create numbered lists and/or a gantt chart?

**Comment by katrinleinweber** [comment]
Thanks for the reminder :-)
