### ISSUE TITLE
"Pygments" error? 

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#53]
In building the page with blog posting instructions, it throws this error:

> WARNING:  Pygments lexer name '' is not known

The pages appear to look OK.  Need to troubleshoot.

**Comment by jduckles** [comment]
This has to do with Pygments now knowing what language the snippets are written in. It may try to guess, but it is probably failing since they're not really in any programming language.

**Comment by maneesha** [comment]
Closing as I don't get this error anymore.
