### ISSUE TITLE
clarification request in tag selection guide

### ISSUE THREAD

**Issue by mfoos** [carpentries/handbook#539]
With the emphasis on "less is more" it's not clear to me whether including the "Data Carpentry" tag is desired, or whether that will be done automatically as part of a port to the central blog. Thanks!

**Comment by serahrono** [comment]
Hey @mfoos, great question. 

For tags on posts in the Data Carpentry blog, there is no need to add `Data Carpentry` as a tag as all posts there are on that subject. 

However, if a community member wanted to narrate their experience from contributing to /working with Data Carpentry resources or running a Data Carpentry workshop and have this published on the central Carpentries blog (carpentries.org/blog), we would then apply a Data Carpentry tag to the post.

**Comment by serahrono** [comment]
I have now [updated the guide to reflect this](https://github.com/carpentries/handbook/blob/master/topic_folders/communications/guides/select-blog-tags.md#carpentries-tagathon). Changes to text in the handbook will take a few hours to propagate, but thanks a bunch for the nudge @mfoos!

**Comment by maneesha** [comment]
Thanks for updating this @serahrono 

Can we close this issue?
