### ISSUE TITLE
Create dictionary for blog post tags

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#542]
We should have a list of all blog post tags with a short definition of how each is to be used.

**Comment by maneesha** [comment]
Hi @serahrono  Are you still working on the blog post tagging project? There are a couple of issues here as well as in our other four websites about tags that I'd like to address or close as appropriate.

**Comment by maneesha** [comment]
@kmomar @acrall We have a number of issues about tags on blog post that have been open for up to two years. Do you want to keep these open?

**Comment by kmomar** [comment]
@maneesha @acrall this and the other blog post issues are a good task for me to focus on in my next reading and reflection day. Let's keep them open till the end of the month, and I'll close them out.
