### ISSUE TITLE
Code of Conduct Sentence

### ISSUE THREAD

**Issue by kekoziar** [carpentries/handbook#553]
It states in the first paragraph of the code of conduct, 

> Any form or behaviour to exclude, intimidate, or cause discomfort is a violation of the Code of Conduct.

Should it be "any form _or_ behaviour" or "any form _of_ behaviour"?

**Comment by maneesha** [comment]
Yes, thanks for catching this @kekoziar 

Would you like to submit a PR? (no worries if not; I can do this - just wanted to give you the chance)

**Comment by kekoziar** [comment]
@maneesha I'll do it.  Thanks!

**Comment by maneesha** [comment]
Closing; fixed with #554 
Thanks @kekoziar !
