### ISSUE TITLE
add mention of workshop website helper page

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/handbook#555]
the workshop website template has now a page with some information for helpers (https://carpentries.github.io/workshop-template/helpers/index.html). It might be useful to list it in the checklists for Instructors.

**Comment by maneesha** [comment]
Thanks @fmichonneau 

@sheraaronhurt  Is there anything specific you think this should say from the Workshop Admin perspective?

**Comment by maneesha** [comment]
We currently have [an instructor checklist](https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#instructor-checklist) and a [helper checklist](https://docs.carpentries.org/topic_folders/hosts_instructors/hosts_instructors_checklist.html#helper-checklist) in the handbook.

@sheraaronhurt  Do you think that the page @fmichonneau  mentioned should be listed anywhere here as a resource?

**Comment by sheraaronhurt** [comment]
@maneesha where does the page that @fmichonneau live? How would a person get to this page? This will help me understand where this information could live.

**Comment by maneesha** [comment]
Good question, @sheraaronhurt !

@fmichonneau  - how do you get to this page from the workshop page?

**Comment by fmichonneau** [comment]
Only by knowing the URL at the moment. There is no link on the page to avoid confusion for the workshop participants.

**Comment by maneesha** [comment]
Thanks.  I don't think it makes sense to link it from the handbook then, since there isn't much content on the helpers page.  It would just refer back to where it came from.  

@sheraaronhurt Happy to consider things if you think it should be linked; otherwise we can close this issue.

**Comment by fmichonneau** [comment]
There isn't information on the page itself but regularly, instructors want to share workshop-specific information with the helpers. I think that having a mention that this page exists for instructors to customize to share info with their helpers would be useful to have in the handbook. I'll submit a short blurb as a PR for this for you all to review.

**Comment by sheraaronhurt** [comment]
We will be adding an automated email to remind Instructors/Hosts to email helpers. We can link this there.

**Comment by maneesha** [comment]
Thanks @sheraaronhurt .
So do you think it also belongs in the handbook or should we just reference it in the email?

**Comment by maneesha** [comment]
Pinging @sheraaronhurt

**Comment by sheraaronhurt** [comment]
@maneesha we can just reference it in the email. I am making a note of this page now :)

**Comment by maneesha** [comment]
Thanks @sheraaronhurt  
In that case I will close this issue.
