### ISSUE TITLE
Mentoring groups info?

### ISSUE THREAD

**Issue by tobyhodges** [carpentries/handbook#56]
Will we move the information about the mentoring groups program into these docs too?

**Comment by maneesha** [comment]
Good question. I think it would be good to have protocols for how the groups come about and work.  @kariljordan  what do you think?

**Comment by kariljordan** [comment]
Yes that sounds good. We are still working through program details though.

**Comment by maneesha** [comment]
Thanks @kariljordan 
Assigning to you for whenever it is ready.

**Comment by kariljordan** [comment]
I had a look at the current [draft](https://github.com/carpentries/usersguides/blob/master/drafts/mentoring-groups.md) for the mentoring groups part of the userguides and I'm happy leaving it as is. We will be keeping this format, and as there are changes made (for example, after we pilot the topic based discussion sessions) I can do a PR to the main user guide to update. So I think we are good to go now.

**Comment by maneesha** [comment]
Fixed with 54a54c877
