### ISSUE TITLE
Instructor tips should include "Talk to an instructor who's taught it before"

### ISSUE THREAD

**Issue by angela-li** [carpentries/handbook#568]
It would be great if this [set of instructor preparation tips](https://github.com/carpentries/handbook/blob/master/topic_folders/hosts_instructors/instructor_tips.md) included more specifically instructions to discuss the curriculum with someone's who's taught it before (if they happen to be at the same location, you could even remote call someone and get some tips). Perhaps "Join a Community Discussion" / "Read the Instructor Notes" could be grouped into this? 

The main point is that instructors should think of talking to their Carpentries "colleagues"/knowledge sharing as a key tactic (as suggested in Instructor Training) for leading a workshop, rather than something they could potentially do.

**Comment by maneesha** [comment]
Thanks for sharing this suggestion @angela-li !

@sheraaronhurt  Do you have any feedback from the workshop admin perspective?

Angela, would you like to submit a PR?

**Comment by sheraaronhurt** [comment]
@maneesha that is a great suggestion. @angela-li thanks for sharing :)

**Comment by maneesha** [comment]
I would be happy for @angela-li  to have the opportunity to submit a PR.  No worries if you can't get to it now, Angela - I can put something in.  Just let me know!
