### ISSUE TITLE
Broken link to, and outdated info on, Zoom page

### ISSUE THREAD

**Issue by lexnederbragt** [carpentries/handbook#572]
`topic_folders/instructor_training/trainers_guide.md` links to the Zoom guide with this link: ../communications/zoom_rooms.html#zoom-manual. This leads to a dead link. The full correct url ishttps://docs.carpentries.org/topic_folders/communications/tools/zoom_rooms.html - not sure how to correct that in the markdown file.

On that Zoom Rooms page, the room for teaching demos is still listed under carpentriesroom3, this has recently been changed to carpentriesroom2.

**Comment by maneesha** [comment]
Thanks for catching this, @lexnederbragt 
This should be fixed by #573  and #574 

In addition to what you've noted, I've also updated some other information about how we use Zoom.   If you see anything else that needs fixing, please feel free to re-open this issue or start a new one.

**Comment by lexnederbragt** [comment]
Thanks! I think this sentence is outdated: "when you are in the Zoom meeting room but unintentionally not as the host, look for the button ‘Claim host’ (click on the ‘Participants’ button; you’ll be asked for a 6-digit host key, which you can find (after logging in to Zoom), at the bottom of the profile, see the explanation here." -> trainers are not logging in to zoom with Carpentries credentials, right? They use the 'claim host code' as described earlier on the page.

**Comment by maneesha** [comment]
@lexnederbragt  Yes, I think that your point above should be in the Instructor Training repo.  Would you like to open an issue there?

**Comment by lexnederbragt** [comment]
Of course. I submitted a PR even :-) https://github.com/carpentries/instructor-training/pull/1113
