### ISSUE TITLE
add information about curriculum development roles

### ISSUE THREAD

**Issue by ErinBecker** [carpentries/handbook#58]
What are the roles and responsibilities of:

- [Curriculum Advisors](https://docs.google.com/document/d/1wIi2CY0fg4LkrlfqbrO47wR-6hR0BE1Qbr5Hu4oeIbg/edit)
- [Lesson Infrastructure Committee Members](https://docs.google.com/document/d/1CfRexJsd0bdYosDO2ExvXL2rl6_Lagp7Io_cQE8hDxw/edit)
- [Maintainers](https://docs.google.com/document/d/1Gujpu9PCUxUlc-NWfVJlYTsRx5jIQwlmHgq8kPobGeE/edit)
- [Translation Coordinators](https://docs.google.com/document/d/1Gujpu9PCUxUlc-NWfVJlYTsRx5jIQwlmHgq8kPobGeE/edit)
- Others?

In each of the cases above, I've linked to existing Google docs outlining these roles. Many of these are quite rudimentary.

**Comment by ErinBecker** [comment]
Not sure whether this information should go here or in the [Curriculum Development](https://github.com/carpentries/curriculum-development) lesson that @fmichonneau is developing.

**Comment by fmichonneau** [comment]
I think it should go in the handbook.

**Comment by ErinBecker** [comment]
This information has been added:

[Curriculum Advisory Committee Roles](http://docs.carpentries.org/topic_folders/lesson_development/lesson_development_roles.html#curriculum-advisory-committee)
[Maintainer Guidelines](http://docs.carpentries.org/topic_folders/maintainers/maintainers.html)

I will add information about Translation coordinators and lesson infrastructure (if it exists).

**Comment by ErinBecker** [comment]
Added info on lesson infrastructure subcommittee roles: https://github.com/carpentries/handbook/pull/119

Translation coordinator role should be part of a separate section "Lesson Translations". Opening a new issue for that.
