### ISSUE TITLE
Logging instructor training/checkout progress

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#67]
We need to include instructions on how to log instructor trainee checkout process.  This may include information that goes in the Instructor Training section as well as the AMY section.

* How trainees report completion of steps
* How this is recorded in AMY
* How certificates are sent out
* How bios make it on the website

**Comment by maneesha** [comment]
@ErinBecker  Do you already have written up anywhere how trainee checkout steps are recorded in AMY?

**Comment by maneesha** [comment]
@weaverbel  I currently have written up instructions on how to format bios to get them on the SWC website.  Will the formatting be the same, and what is the timeline for having this live on the Carpentries website instead?  If it's going to be relatively soon I would  like the instructions for bios to refer to the new website rather than the  existing website.

**Comment by maneesha** [comment]
@ErinBecker   and  @sheraaron   checking in to see if there are instructions written up on how to log trainee checkout progress in AMY.  If not I can work on drafting these from scratch. Thanks!

**Comment by sheraaron** [comment]
@maneesha  I can share with you the document Erin created for me.

**Comment by maneesha** [comment]
@sheraaron  perfect!
Noting the document here:  https://docs.google.com/document/d/1TazCstnaI9-cpyHgXZHop23HrQRZRlFPVooa5mrlcko/edit?ts=5aba8135

I will be adding this information to this site.

**Comment by maneesha** [comment]
Mostly fixed with

43b25c6 link checkout instructions to AMY manual section
bd200b7 screenshots for tracking trainee progress
0f69b89 add instructions to track trainee progress in AMY
e5a962e add training checkout file to index
771df98 move Other Tasks section to end
f766580 add instructions on Accepting Trainee Applications

Starting new issues for steps that remain
