### ISSUE TITLE
AWI Instances Instructions

### ISSUE THREAD

**Issue by sheraaron** [carpentries/handbook#78]
Can we have the instructions for launching the amazon instances in the guidebook?

**Comment by tracykteal** [comment]
We could for in general. For us to start them in requires login information, and we couldn't include that publicly. 

I think @ErinBecker @maneesha @elizabethwilliams8 are thinking of the best way to share staff information.

**Comment by maneesha** [comment]
@sheraaron  That is a good question.  Right now the instructions live with the Data Carpentry lessons.  See http://www.datacarpentry.org/cloud-genomics/02-logging-onto-cloud/ and https://github.com/datacarpentry/cloud-genomics/blob/gh-pages/_episodes/02-logging-onto-cloud.md.

I will defer to @ErinBecker  and her team of lesson maintainers on the best place to put this information.

**Comment by maneesha** [comment]
We will keep this with the genomics lesson.
