### ISSUE TITLE
Bug BBQ page has empty sections

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#80]
These sections of the Bug BBQ are empty.  @ErinBecker @fmichonneau  is there something you want to add in here, or should we remove those sections for now?

##### Announcing Bug BBQ (Maintainer list)

**Comment by maneesha** [comment]
@ErinBecker  and @fmichonneau Do you want to take these sections out for now, so that we are not publishing the site with empty sections? 
Or do you have info I can put in there?

**Comment by fmichonneau** [comment]
I suggest we remove it for now. I'll work on this in the next week as we prepare for the April bug BBQ, and can add the information as needed. Please leave the issue open for now though.

**Comment by maneesha** [comment]
Fixed with 6a320c742b54218b83f6175d6b
but keeping issue open

**Comment by fmichonneau** [comment]
closing in favor of #129
