### ISSUE TITLE
Table not rendering

### ISSUE THREAD

**Issue by maneesha** [carpentries/handbook#9]
Trying to add a table for how events are scheduled here: http://docs.carpentries.org/instructor_training/scheduling_training_events.html

This does not render properly.  Possible fix:  
https://stackoverflow.com/questions/44461762/sphinx-is-not-recognising-my-markdown-tables

**Comment by tobyhodges** [comment]
Tables are notoriously unreliable in Markdown - unsupported in a lot of renderers. Depending on how many tables you think we're likely to use in the handbook, one easy fix might be to describe the table in raw HTML instead. I guess that will render ok via Sphinx? Not a great solution for lots of tables, but ok if this is the only one?

**Comment by maneesha** [comment]
Site structure has changed so table in question is now here:
http://docs.carpentries.org/topic_folders/instructor_training/scheduling_training_events.html

https://github.com/carpentries/usersguides/blob/master/topic_folders/instructor_training/scheduling_training_events.md

**Comment by maneesha** [comment]
Can't figure out an easy way to make this work so this is now a narrative, not a table.
Re-open if anyone ever figures out tables.
See ec6c272c

**Comment by jduckles** [comment]
FYI: Made tables work using [this extension](https://github.com/ryanfox/sphinx-markdown-tables), it has been added to the `requirements.txt` for this repo and the build environment has it now too.
