### ISSUE TITLE
make code of conduct more visible

### ISSUE THREAD

**Issue by fmichonneau** [carpentries/handbook#94]
currently we have to click down 3 levels in the menu to find the code of conduct. Could the main text be its own section, and maintain the enforcement in the policies section? Alternatively, we could have

```
CODE OF CONDUCT <- this would have the full text
  + Code of Conduct Enforcement Manual
  + Code of Conduct Reporting Guide
```

**Comment by ErinBecker** [comment]
I'm working on putting in a PR for this right now @fmichonneau.

**Comment by fmichonneau** [comment]
I'd like to suggest that the code of conduct be its own section, and not be under "policies".
